language: go
go:
- 1.5
env:
  global:
  - secure: "Ffv0t508yBkuWsee2mRAE3ngW7BoOJ9hSvRDCmfNbvINO+u81SrqKBmsXRY3ip0pZxFkf0842WYG1ZdPes74YZUKCcrDp4MwcAKkMaNX8iYiRfFDtGSvMfHRrHzTb+QsiCeuEsMKCllqO6Vpqfb+ZlZ8VfvZYm4vOx4mR76dX4GYR6Ze60ac+6RRAeqQxe1q8/96kvyNmVuHLxuGTPSyCOe3rnHxcfdQHJcJt7GThI8/tZbSyl65u7p1/TDnfIwFjrrFcNsdPrp45fYO6Z8e1hxH8bdn6O5pGrmvpIB5Ykx6eupP6I4tpRp6z8t7gMlanGJNLAzgarr509bAE/zzeD2Y8KE38vlT9LgBzy1r4gyMaCMn5CNXaDgBEXTD2Ufnn+pSl495QCz4Ux5x/1jwA1q5hDVMZvJ0FZJBZzSwOwgQTGewoyE0smoOG5SgKvy/NZUce6xZ2fDKl7gC/80NBHXszNiq5wneJD855z05WgbhwX036ctgsm+xdO8eWxp8PzP+dmKUMXUtv6sAPgd6qkmOMpfU+OHYEK/IKNIcDnqJXWO+/CLWcUEQltuCBVU5anhIYgMbjwGDch6kpWYm+k/ySsG7C7Dr1pmDvFtwkZap3otUc78Oi6afC7155o3TweNb0YjAXtDlP+mbopeL3/ekOa/RKc5V0Qatq4jYouk="
  - secure: "XMF2Hn6cD7FddNMCBt5ZehHTj92isDmTkN/s5G0PmKkCPbHNRgwKSorDzBuAOBBv40YgCTSkJYyYTQR1ZyfjNK9sPdSJfuNtgnI+w+RvfwkNqdFvHRkxPorQL6aI1HD9ddJ8ueiYtz4h8WtKs/ZRoipviji6bsXoLsPSuTZ88ohE9B3zEVH2zafZ+X4xap897jqahejHRuX8aG9BVP/6lwzj8R2TY4oTJUrYKkVGe3d58u13GX5e9yNvKX5UW8oUeMT3K0Ssks8edWEjtDn7+ZWjWzJ1BQ+IjUXupeL1aG5bpbTQOY4SfHyNp+cwGm6HogIBcECsqv1vBW5T3W2JYbYA/eOsrUa2mQ+84pSBGUkceHlTGE2G/lxbfn20rXQPNwKLF3itIYhTMZXEo1GrkdbC+bou03QOvc4VF85beGnJANSP3Aq3nS7pHXfDTAbG/bN8dA4/Q0tJ8OCYNSi0xP7am5aCoD2MHVoEEQZDb2aJS6KC4JjKV8CnSQuvNWj2qHoGPu4pubQWUus4AMHpYtuEIunPNw79iF9NhVfwosFCS/V9IIhMC101ZQlKAFkK12zzTEzksAHqpQEGb1p1H0K5glp2PH3sEyvOWB8tK/87EqE+nBoyXhMPbC0n0ePqb5x0qJsnorfVvme2zQLbk+q1fTV1oftdmYASz5Dwfak="
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
be fore_deploy:
- make rpm deb
- pwd
- go get github.com/aktau/github-release
- echo $GITHUB_TEST
deploy:
- provider: script
  script: script/travis/github-releases.sh
  on:
    repo: stanaka/mkr
    all_branches: true
