language: go
go:
- 1.5
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
before_deploy:
- make rpm deb
- pwd
- go get github.com/aktau/github-release
deploy:
  - provider: script
    script: script/travis/github-releases.sh
    on:
      repo: stanaka/mkr
      all_branches: true
