language: go
go:
- 1.5
env:
  global:
  - PATH=~/bin:~/gopath/bin:$PATH
  - secure: "Ffv0t508yBkuWsee2mRAE3ngW7BoOJ9hSvRDCmfNbvINO+u81SrqKBmsXRY3ip0pZxFkf0842WYG1ZdPes74YZUKCcrDp4MwcAKkMaNX8iYiRfFDtGSvMfHRrHzTb+QsiCeuEsMKCllqO6Vpqfb+ZlZ8VfvZYm4vOx4mR76dX4GYR6Ze60ac+6RRAeqQxe1q8/96kvyNmVuHLxuGTPSyCOe3rnHxcfdQHJcJt7GThI8/tZbSyl65u7p1/TDnfIwFjrrFcNsdPrp45fYO6Z8e1hxH8bdn6O5pGrmvpIB5Ykx6eupP6I4tpRp6z8t7gMlanGJNLAzgarr509bAE/zzeD2Y8KE38vlT9LgBzy1r4gyMaCMn5CNXaDgBEXTD2Ufnn+pSl495QCz4Ux5x/1jwA1q5hDVMZvJ0FZJBZzSwOwgQTGewoyE0smoOG5SgKvy/NZUce6xZ2fDKl7gC/80NBHXszNiq5wneJD855z05WgbhwX036ctgsm+xdO8eWxp8PzP+dmKUMXUtv6sAPgd6qkmOMpfU+OHYEK/IKNIcDnqJXWO+/CLWcUEQltuCBVU5anhIYgMbjwGDch6kpWYm+k/ySsG7C7Dr1pmDvFtwkZap3otUc78Oi6afC7155o3TweNb0YjAXtDlP+mbopeL3/ekOa/RKc5V0Qatq4jYouk="
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_script:
- make cover
after_success:
- script/travis/autotag.sh
before_deploy:
- make rpm deb
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
- git fetch
- git checkout -b master origin/master
- git diff --word-diff origin/master..bump-version-0.9.4
- git checkout $TRAVIS_BRANCH
deploy:
- provider: script
  script: script/travis/github-releases.sh
  skip_cleanup: true
  on:
    repo: stanaka/mkr
    branch: master
- provider: script
  script: script/releng --task=create-pullrequest --current-branch=$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: stanaka/mkr
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
