language: go
go:
- 1.5
env:
- PATH=/home/travis/gopath/bin:$PATH
- secure: zb++krzY4Rt7Q+HXPrG8D+oe89LSV4s0MxrjBcU85UDMI+NC+gfJTzkH5Rctt9zYb57sUX9TgiiaN9b7947kU1uMQWYRVaW2THSMGQwH5wflEsTJ2EhVfScq0+T9Qik3UUaFZwK3ah1dnriHeCFXISW42iah0wwMTmdnq60CBSy82uEhKxSJNpfCyciMtO7DHJdHkUNHmw3Ql8Lf2cIa4g9Sp7+zWVGw3CoSOTZVsyzt1umKzqq9gGXLpJpkKKWil/djlYa4+WpONsfJ4ecfRw3zBz+1Cnc2JsZ3ng2LIjusR6u0FuKXSEMg2lYxsn6EoLjm8xVSfyB0FKwP8iJG/W3vhNQnATMyAeWMROpQfKPc5LpJbZpFtvsLKa5IRL/SRwRIgSBm8uCkakg3pyzmmiztX+WTVNTNFmzGT9lPXIJs3yEruewlCQ0xfrBfMLaEnlsBAriaeNaI4N6q8Qkpvl3LeEIiy81/+VzAV7/ZbTciMArYqkaq5RFKiRP95d9R+ZIO7bv3V30DettV1PD+NpvAT1HRWpqCSsRoYax6YynIKCd4eYCIHap7utHfQ+pTVYZJ0+OPHjBzqKETU8SNjrVqa3wa9ZEbS13mdYK2UBUZQI0W74IgBGV/gCe4lZVvquyv2eclmS2a9D/0KAF6+A9exN5xHxhywBofgsm2EzM=
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
before_deploy:
- make rpm deb
- pwd
- go get github.com/aktau/github-release
deploy:
- provider: script
  script: script/travis/github-releases.sh
  on:
    repo: stanaka/mkr
    all_branches: true
