language: go
go:
- 1.14.x
env:
  global:
  - GO111MODULE=on
  - PATH=~/bin:~/gopath/bin:$PATH
  - secure: "v7OavKE9nG0icMYF4HgLrk1LMAK94Wp7BCjragd9IdxumuXTvWensXG17aUb8ofkkO44M6+/o8em30D0Xnmj1YMoADO2647T1eWqKWecMA4eNCo6QyuxKL+5K0QwXl+OOM4jHcziWReJO1452k1OyL554EJQZr8MJ5JP2gVISEN4oV9BEaS6S0/CEySpo8psIyR5M281jXdCQrHtjBbSXUTs5QBdT1yxAxvDMqPhECNds1iMtA0VnDPbK1HOENAVheaMipSXqpT04TmMK7UfGJdvfdV3Qk+mKtnIjMB9KRQOPDGjY/qbXCyAeqOaBk+r/41d+ij04qtv5JNN0bpGH+bW+z+GmaGRpOF+/zveOLSWG3iJc3ETCbnkXfJjpABr+kumg5SBEDgzx5v1f49QWVUFKDGndda4idhsGy8GQO4yY5Bnv/uD5hDNQW5Enyrw4OwqeNu5uvN54lXosjpSpbBvZ1qptiH1vV1PfVEJfmMn2oAuNYDHweL7IMRH+q7wcLJQJA8Q0dOvoWVNfiY0msQrGUIii7/gMidcYCLDKLF83++KT1cnfqdhOdMP/LMQGViTmJqZXWEKEyVpXt1twZnYv56AW+9o9VCVa7nO9059fDpCdoMgxuNjoY/DOEmRq5LutMBq7MQhp2VPdDY82f0GeyQFB04sbpyHUi4F/Uo="
install:
- sudo apt-get update
- >-
  DEBIAN_FRONTEND=noninteractive
  sudo apt-get install -y
  rpm devscripts debhelper fakeroot crossbuild-essential-arm64 crossbuild-essential-armhf
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_script:
- make cover
before_deploy:
- go get github.com/x-motemen/gobump/cmd/gobump
- go get github.com/mackerelio/golib/cmd/mackerel-github-release
deploy:
- provider: script
  script: mackerel-github-release && mackerel-github-release -staging
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: MegndYQrf9ubVA015qCORCIYows50jYmAUKNNPXZOlWRkzhIir2XVzK6m2vgZPxKmQpwcg0n1tAddmxw2lHwTC+V31UNTHaItNYo5RjRkRSC6Js1FlGeKHb/ccu0GeDy8mPo4OAiFxvQe3qY889qQ3k5Ke22fE7PGZMpC5+4/CA=
