language: go
go:
- 1.14.x
env:
  global:
  - GO111MODULE=on
  - PATH=~/bin:~/gopath/bin:$PATH
  - secure: "PDv5k+Wp7fEHGN2oszqpN/7Lvcc6bY4wT9PgT0w+G8AUNOhprXzPzIHVP2qNIBfhIDjECrbw4T6h1PeumIZYXg3wqLElGe+24OfDjSPjB3nal40Sx9PLLG5h7ywsJlPMqV0bfKyYTxs0lmUhE5XaaBvHEJGv6MHNjBc2H0bVMsE="
install:
- sudo apt-get update
- >-
  DEBIAN_FRONTEND=noninteractive
  sudo apt-get install -y
  rpm devscripts debhelper fakeroot crossbuild-essential-arm64 crossbuild-essential-armhf
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_script:
- make cover
before_deploy:
- go get github.com/x-motemen/gobump/cmd/gobump
- go get github.com/mackerelio/golib/cmd/mackerel-github-release
deploy:
- provider: script
  script: mackerel-github-release && mackerel-github-release -staging
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: MegndYQrf9ubVA015qCORCIYows50jYmAUKNNPXZOlWRkzhIir2XVzK6m2vgZPxKmQpwcg0n1tAddmxw2lHwTC+V31UNTHaItNYo5RjRkRSC6Js1FlGeKHb/ccu0GeDy8mPo4OAiFxvQe3qY889qQ3k5Ke22fE7PGZMpC5+4/CA=
