#!/usr/bin/env perl

=head DESCRIPTION

releng script for mkr

=head SYNOPSIS

    % tool/create-release-pullrequest

=head DEPENDENCY

`git`, `hub` and `gobump` command are required.

=cut

use 5.014;
use strict;
use warnings;
use utf8;

use File::Copy qw/move/;
use Mackerel::ReleaseUtils qw/create_release_pull_request/;

create_release_pull_request 'mkr' => sub {
    my ($current_version, $next_version, $releases) = @_;

    move
        "packaging/mkr_$current_version.orig.tar.gz",
        "packaging/mkr_$next_version.orig.tar.gz";
};
