name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        default: '0.0.0'

env:
  GIT_AUTHOR_NAME: mackerelbot
  GIT_AUTHOR_EMAIL: mackerel-developers@hatena.ne.jp
  GIT_COMMITTER_NAME: mackerelbot
  GIT_COMMITTER_EMAIL: mackerel-developers@hatena.ne.jp

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: shogo82148/actions-setup-perl@v1

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**\go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - run: go get github.com/x-motemen/gobump/cmd/gobump
    - run: go get github.com/Songmu/ghch/cmd/ghch

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create PR
      run: make release ARGS="${{ github.event.inputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
